/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1beta1StatefulSetStatus = factory(root.KubernetesJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1beta1StatefulSetStatus model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1beta1StatefulSetStatus
   * @version 1.0.0-snapshot
   */

  /**
   * Constructs a new <code>V1beta1StatefulSetStatus</code>.
   * StatefulSetStatus represents the current state of a StatefulSet.
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1beta1StatefulSetStatus
   * @class
   * @param replicas {Number} Replicas is the number of actual replicas.
   */
  var exports = function(replicas) {
    var _this = this;


    _this['replicas'] = replicas;
  };

  /**
   * Constructs a <code>V1beta1StatefulSetStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1StatefulSetStatus} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1StatefulSetStatus} The populated <code>V1beta1StatefulSetStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('observedGeneration')) {
        obj['observedGeneration'] = ApiClient.convertToType(data['observedGeneration'], 'Number');
      }
      if (data.hasOwnProperty('replicas')) {
        obj['replicas'] = ApiClient.convertToType(data['replicas'], 'Number');
      }
    }
    return obj;
  }

  /**
   * most recent generation observed by this StatefulSet.
   * @member {Number} observedGeneration
   */
  exports.prototype['observedGeneration'] = undefined;
  /**
   * Replicas is the number of actual replicas.
   * @member {Number} replicas
   */
  exports.prototype['replicas'] = undefined;



  return exports;
}));


