/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1ContainerStateTerminated = factory(root.KubernetesJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1ContainerStateTerminated model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1ContainerStateTerminated
   * @version 1.0.0-snapshot
   */

  /**
   * Constructs a new <code>V1ContainerStateTerminated</code>.
   * ContainerStateTerminated is a terminated state of a container.
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1ContainerStateTerminated
   * @class
   * @param exitCode {Number} Exit status from the last termination of the container
   */
  var exports = function(exitCode) {
    var _this = this;


    _this['exitCode'] = exitCode;





  };

  /**
   * Constructs a <code>V1ContainerStateTerminated</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1ContainerStateTerminated} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1ContainerStateTerminated} The populated <code>V1ContainerStateTerminated</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('containerID')) {
        obj['containerID'] = ApiClient.convertToType(data['containerID'], 'String');
      }
      if (data.hasOwnProperty('exitCode')) {
        obj['exitCode'] = ApiClient.convertToType(data['exitCode'], 'Number');
      }
      if (data.hasOwnProperty('finishedAt')) {
        obj['finishedAt'] = ApiClient.convertToType(data['finishedAt'], 'Date');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('signal')) {
        obj['signal'] = ApiClient.convertToType(data['signal'], 'Number');
      }
      if (data.hasOwnProperty('startedAt')) {
        obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Container's ID in the format 'docker://<container_id>'
   * @member {String} containerID
   */
  exports.prototype['containerID'] = undefined;
  /**
   * Exit status from the last termination of the container
   * @member {Number} exitCode
   */
  exports.prototype['exitCode'] = undefined;
  /**
   * Time at which the container last terminated
   * @member {Date} finishedAt
   */
  exports.prototype['finishedAt'] = undefined;
  /**
   * Message regarding the last termination of the container
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * (brief) reason from the last termination of the container
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;
  /**
   * Signal from the last termination of the container
   * @member {Number} signal
   */
  exports.prototype['signal'] = undefined;
  /**
   * Time at which previous execution of the container started
   * @member {Date} startedAt
   */
  exports.prototype['startedAt'] = undefined;



  return exports;
}));


