/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1ObjectFieldSelector = factory(root.KubernetesJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1ObjectFieldSelector model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1ObjectFieldSelector
   * @version 1.0.0-snapshot
   */

  /**
   * Constructs a new <code>V1ObjectFieldSelector</code>.
   * ObjectFieldSelector selects an APIVersioned field of an object.
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1ObjectFieldSelector
   * @class
   * @param fieldPath {String} Path of the field to select in the specified API version.
   */
  var exports = function(fieldPath) {
    var _this = this;


    _this['fieldPath'] = fieldPath;
  };

  /**
   * Constructs a <code>V1ObjectFieldSelector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1ObjectFieldSelector} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1ObjectFieldSelector} The populated <code>V1ObjectFieldSelector</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiVersion')) {
        obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
      }
      if (data.hasOwnProperty('fieldPath')) {
        obj['fieldPath'] = ApiClient.convertToType(data['fieldPath'], 'String');
      }
    }
    return obj;
  }

  /**
   * Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
   * @member {String} apiVersion
   */
  exports.prototype['apiVersion'] = undefined;
  /**
   * Path of the field to select in the specified API version.
   * @member {String} fieldPath
   */
  exports.prototype['fieldPath'] = undefined;



  return exports;
}));


