/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1SubjectAccessReviewStatus = factory(root.KubernetesJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1SubjectAccessReviewStatus model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1SubjectAccessReviewStatus
   * @version 1.0.0-snapshot
   */

  /**
   * Constructs a new <code>V1SubjectAccessReviewStatus</code>.
   * SubjectAccessReviewStatus
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1SubjectAccessReviewStatus
   * @class
   * @param allowed {Boolean} Allowed is required.  True if the action would be allowed, false otherwise.
   */
  var exports = function(allowed) {
    var _this = this;

    _this['allowed'] = allowed;


  };

  /**
   * Constructs a <code>V1SubjectAccessReviewStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1SubjectAccessReviewStatus} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1SubjectAccessReviewStatus} The populated <code>V1SubjectAccessReviewStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowed')) {
        obj['allowed'] = ApiClient.convertToType(data['allowed'], 'Boolean');
      }
      if (data.hasOwnProperty('evaluationError')) {
        obj['evaluationError'] = ApiClient.convertToType(data['evaluationError'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
    }
    return obj;
  }

  /**
   * Allowed is required.  True if the action would be allowed, false otherwise.
   * @member {Boolean} allowed
   */
  exports.prototype['allowed'] = undefined;
  /**
   * EvaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request.
   * @member {String} evaluationError
   */
  exports.prototype['evaluationError'] = undefined;
  /**
   * Reason is optional.  It indicates why a request was allowed or denied.
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;



  return exports;
}));


