/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient', 'io.kubernetes.js/io.kubernetes.js.models/V1UserInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1UserInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1TokenReviewStatus = factory(root.KubernetesJsClient.ApiClient, root.KubernetesJsClient.V1UserInfo);
  }
}(this, function(ApiClient, V1UserInfo) {
  'use strict';




  /**
   * The V1TokenReviewStatus model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1TokenReviewStatus
   * @version 1.0.0-snapshot
   */

  /**
   * Constructs a new <code>V1TokenReviewStatus</code>.
   * TokenReviewStatus is the result of the token authentication request.
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1TokenReviewStatus
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>V1TokenReviewStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1TokenReviewStatus} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1TokenReviewStatus} The populated <code>V1TokenReviewStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authenticated')) {
        obj['authenticated'] = ApiClient.convertToType(data['authenticated'], 'Boolean');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = V1UserInfo.constructFromObject(data['user']);
      }
    }
    return obj;
  }

  /**
   * Authenticated indicates that the token was associated with a known user.
   * @member {Boolean} authenticated
   */
  exports.prototype['authenticated'] = undefined;
  /**
   * Error indicates that the token couldn't be checked
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * User is the UserInfo associated with the provided token.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1UserInfo} user
   */
  exports.prototype['user'] = undefined;



  return exports;
}));


