/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1ObjectMeta from './V1ObjectMeta';





/**
* The V1alpha1PriorityClass model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1alpha1PriorityClass
* @version 0.3-SNAPSHOT
*/
export default class V1alpha1PriorityClass {
    /**
    * Constructs a new <code>V1alpha1PriorityClass</code>.
    * PriorityClass defines mapping from a priority class name to the priority integer value. The value can be any valid integer.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1alpha1PriorityClass
    * @class
    * @param value {Number} The value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec.
    */

    constructor(value) {
        

        
        

        this['value'] = value;

        
    }

    /**
    * Constructs a <code>V1alpha1PriorityClass</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1alpha1PriorityClass} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1alpha1PriorityClass} The populated <code>V1alpha1PriorityClass</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1alpha1PriorityClass();

            
            
            

            if (data.hasOwnProperty('apiVersion')) {
                obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('globalDefault')) {
                obj['globalDefault'] = ApiClient.convertToType(data['globalDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = V1ObjectMeta.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
    * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
    * @member {String} apiVersion
    */
    apiVersion = undefined;
    /**
    * description is an arbitrary string that usually provides guidelines on when this priority class should be used.
    * @member {String} description
    */
    description = undefined;
    /**
    * globalDefault specifies whether this PriorityClass should be considered as the default priority for pods that do not have any priority class. Only one PriorityClass can be marked as `globalDefault`. However, if more than one PriorityClasses exists with their `globalDefault` field set to true, the smallest value of such global default PriorityClasses will be used as the default priority.
    * @member {Boolean} globalDefault
    */
    globalDefault = undefined;
    /**
    * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
    * @member {String} kind
    */
    kind = undefined;
    /**
    * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1ObjectMeta} metadata
    */
    metadata = undefined;
    /**
    * The value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec.
    * @member {Number} value
    */
    value = undefined;








}


