/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1beta1NetworkPolicyPort model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1beta1NetworkPolicyPort
* @version 0.3-SNAPSHOT
*/
export default class V1beta1NetworkPolicyPort {
    /**
    * Constructs a new <code>V1beta1NetworkPolicyPort</code>.
    * DEPRECATED 1.9 - This group version of NetworkPolicyPort is deprecated by networking/v1/NetworkPolicyPort.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1beta1NetworkPolicyPort
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1NetworkPolicyPort</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1beta1NetworkPolicyPort} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1beta1NetworkPolicyPort} The populated <code>V1beta1NetworkPolicyPort</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1NetworkPolicyPort();

            
            
            

            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], Object);
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
        }
        return obj;
    }

    /**
    * If specified, the port on the given protocol.  This can either be a numerical or named port on a pod.  If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
    * @member {Object} port
    */
    port = undefined;
    /**
    * Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.
    * @member {String} protocol
    */
    protocol = undefined;








}


