/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1ContainerStateWaiting model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1ContainerStateWaiting
* @version 0.3-SNAPSHOT
*/
export default class V1ContainerStateWaiting {
    /**
    * Constructs a new <code>V1ContainerStateWaiting</code>.
    * ContainerStateWaiting is a waiting state of a container.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1ContainerStateWaiting
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1ContainerStateWaiting</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1ContainerStateWaiting} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1ContainerStateWaiting} The populated <code>V1ContainerStateWaiting</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ContainerStateWaiting();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }

    /**
    * Message regarding why the container is not yet running.
    * @member {String} message
    */
    message = undefined;
    /**
    * (brief) reason the container is not yet running.
    * @member {String} reason
    */
    reason = undefined;








}


