/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1ConfigMapKeySelector from './V1ConfigMapKeySelector';
import V1ObjectFieldSelector from './V1ObjectFieldSelector';
import V1ResourceFieldSelector from './V1ResourceFieldSelector';
import V1SecretKeySelector from './V1SecretKeySelector';





/**
* The V1EnvVarSource model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1EnvVarSource
* @version 0.3-SNAPSHOT
*/
export default class V1EnvVarSource {
    /**
    * Constructs a new <code>V1EnvVarSource</code>.
    * EnvVarSource represents a source for the value of an EnvVar.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1EnvVarSource
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1EnvVarSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1EnvVarSource} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1EnvVarSource} The populated <code>V1EnvVarSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1EnvVarSource();

            
            
            

            if (data.hasOwnProperty('configMapKeyRef')) {
                obj['configMapKeyRef'] = V1ConfigMapKeySelector.constructFromObject(data['configMapKeyRef']);
            }
            if (data.hasOwnProperty('fieldRef')) {
                obj['fieldRef'] = V1ObjectFieldSelector.constructFromObject(data['fieldRef']);
            }
            if (data.hasOwnProperty('resourceFieldRef')) {
                obj['resourceFieldRef'] = V1ResourceFieldSelector.constructFromObject(data['resourceFieldRef']);
            }
            if (data.hasOwnProperty('secretKeyRef')) {
                obj['secretKeyRef'] = V1SecretKeySelector.constructFromObject(data['secretKeyRef']);
            }
        }
        return obj;
    }

    /**
    * Selects a key of a ConfigMap.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1ConfigMapKeySelector} configMapKeyRef
    */
    configMapKeyRef = undefined;
    /**
    * Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1ObjectFieldSelector} fieldRef
    */
    fieldRef = undefined;
    /**
    * Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1ResourceFieldSelector} resourceFieldRef
    */
    resourceFieldRef = undefined;
    /**
    * Selects a key of a secret in the pod's namespace
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1SecretKeySelector} secretKeyRef
    */
    secretKeyRef = undefined;








}


