/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1IPBlock from './V1IPBlock';
import V1LabelSelector from './V1LabelSelector';





/**
* The V1NetworkPolicyPeer model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1NetworkPolicyPeer
* @version 0.3-SNAPSHOT
*/
export default class V1NetworkPolicyPeer {
    /**
    * Constructs a new <code>V1NetworkPolicyPeer</code>.
    * NetworkPolicyPeer describes a peer to allow traffic from. Exactly one of its fields must be specified.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1NetworkPolicyPeer
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1NetworkPolicyPeer</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1NetworkPolicyPeer} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1NetworkPolicyPeer} The populated <code>V1NetworkPolicyPeer</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1NetworkPolicyPeer();

            
            
            

            if (data.hasOwnProperty('ipBlock')) {
                obj['ipBlock'] = V1IPBlock.constructFromObject(data['ipBlock']);
            }
            if (data.hasOwnProperty('namespaceSelector')) {
                obj['namespaceSelector'] = V1LabelSelector.constructFromObject(data['namespaceSelector']);
            }
            if (data.hasOwnProperty('podSelector')) {
                obj['podSelector'] = V1LabelSelector.constructFromObject(data['podSelector']);
            }
        }
        return obj;
    }

    /**
    * IPBlock defines policy on a particular IPBlock
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1IPBlock} ipBlock
    */
    ipBlock = undefined;
    /**
    * Selects Namespaces using cluster scoped-labels. This matches all pods in all namespaces selected by this label selector. This field follows standard label selector semantics. If present but empty, this selector selects all namespaces.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1LabelSelector} namespaceSelector
    */
    namespaceSelector = undefined;
    /**
    * This is a label selector which selects Pods in this namespace. This field follows standard label selector semantics. If present but empty, this selector selects all pods in this namespace.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1LabelSelector} podSelector
    */
    podSelector = undefined;








}


