/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1Taint model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V1Taint
* @version 0.3-SNAPSHOT
*/
export default class V1Taint {
    /**
    * Constructs a new <code>V1Taint</code>.
    * The node this Taint is attached to has the \&quot;effect\&quot; on any pod that does not tolerate the Taint.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V1Taint
    * @class
    * @param effect {String} Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
    * @param key {String} Required. The taint key to be applied to a node.
    */

    constructor(effect, key) {
        

        
        

        this['effect'] = effect;this['key'] = key;

        
    }

    /**
    * Constructs a <code>V1Taint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V1Taint} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V1Taint} The populated <code>V1Taint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1Taint();

            
            
            

            if (data.hasOwnProperty('effect')) {
                obj['effect'] = ApiClient.convertToType(data['effect'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('timeAdded')) {
                obj['timeAdded'] = ApiClient.convertToType(data['timeAdded'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
    * @member {String} effect
    */
    effect = undefined;
    /**
    * Required. The taint key to be applied to a node.
    * @member {String} key
    */
    key = undefined;
    /**
    * TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints.
    * @member {Date} timeAdded
    */
    timeAdded = undefined;
    /**
    * Required. The taint value corresponding to the taint key.
    * @member {String} value
    */
    value = undefined;








}


