/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V2beta1PodsMetricSource model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V2beta1PodsMetricSource
* @version 0.3-SNAPSHOT
*/
export default class V2beta1PodsMetricSource {
    /**
    * Constructs a new <code>V2beta1PodsMetricSource</code>.
    * PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V2beta1PodsMetricSource
    * @class
    * @param metricName {String} metricName is the name of the metric in question
    * @param targetAverageValue {String} targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity)
    */

    constructor(metricName, targetAverageValue) {
        

        
        

        this['metricName'] = metricName;this['targetAverageValue'] = targetAverageValue;

        
    }

    /**
    * Constructs a <code>V2beta1PodsMetricSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V2beta1PodsMetricSource} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V2beta1PodsMetricSource} The populated <code>V2beta1PodsMetricSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2beta1PodsMetricSource();

            
            
            

            if (data.hasOwnProperty('metricName')) {
                obj['metricName'] = ApiClient.convertToType(data['metricName'], 'String');
            }
            if (data.hasOwnProperty('targetAverageValue')) {
                obj['targetAverageValue'] = ApiClient.convertToType(data['targetAverageValue'], 'String');
            }
        }
        return obj;
    }

    /**
    * metricName is the name of the metric in question
    * @member {String} metricName
    */
    metricName = undefined;
    /**
    * targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity)
    * @member {String} targetAverageValue
    */
    targetAverageValue = undefined;








}


