/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1LabelSelector from './V1LabelSelector';





/**
* The V2beta1ExternalMetricSource model module.
* @module io.kubernetes.client/io.kubernetes.client.models/V2beta1ExternalMetricSource
* @version 0.3-SNAPSHOT
*/
export default class V2beta1ExternalMetricSource {
    /**
    * Constructs a new <code>V2beta1ExternalMetricSource</code>.
    * ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster). Exactly one \&quot;target\&quot; type should be set.
    * @alias module:io.kubernetes.client/io.kubernetes.client.models/V2beta1ExternalMetricSource
    * @class
    * @param metricName {String} metricName is the name of the metric in question.
    */

    constructor(metricName) {
        

        
        

        this['metricName'] = metricName;

        
    }

    /**
    * Constructs a <code>V2beta1ExternalMetricSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:io.kubernetes.client/io.kubernetes.client.models/V2beta1ExternalMetricSource} obj Optional instance to populate.
    * @return {module:io.kubernetes.client/io.kubernetes.client.models/V2beta1ExternalMetricSource} The populated <code>V2beta1ExternalMetricSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2beta1ExternalMetricSource();

            
            
            

            if (data.hasOwnProperty('metricName')) {
                obj['metricName'] = ApiClient.convertToType(data['metricName'], 'String');
            }
            if (data.hasOwnProperty('metricSelector')) {
                obj['metricSelector'] = V1LabelSelector.constructFromObject(data['metricSelector']);
            }
            if (data.hasOwnProperty('targetAverageValue')) {
                obj['targetAverageValue'] = ApiClient.convertToType(data['targetAverageValue'], 'String');
            }
            if (data.hasOwnProperty('targetValue')) {
                obj['targetValue'] = ApiClient.convertToType(data['targetValue'], 'String');
            }
        }
        return obj;
    }

    /**
    * metricName is the name of the metric in question.
    * @member {String} metricName
    */
    metricName = undefined;
    /**
    * metricSelector is used to identify a specific time series within a given metric.
    * @member {module:io.kubernetes.client/io.kubernetes.client.models/V1LabelSelector} metricSelector
    */
    metricSelector = undefined;
    /**
    * targetAverageValue is the target per-pod value of global metric (as a quantity). Mutually exclusive with TargetValue.
    * @member {String} targetAverageValue
    */
    targetAverageValue = undefined;
    /**
    * targetValue is the target value of the metric (as a quantity). Mutually exclusive with TargetAverageValue.
    * @member {String} targetValue
    */
    targetValue = undefined;








}


