/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KubernetesJsClient);
  }
}(this, function(expect, KubernetesJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KubernetesJsClient.Batch_v2alpha1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Batch_v2alpha1Api', function() {
    describe('createNamespacedCronJob', function() {
      it('should call createNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test createNamespacedCronJob
        //instance.createNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createNamespacedScheduledJob', function() {
      it('should call createNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test createNamespacedScheduledJob
        //instance.createNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollectionNamespacedCronJob', function() {
      it('should call deleteCollectionNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test deleteCollectionNamespacedCronJob
        //instance.deleteCollectionNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollectionNamespacedScheduledJob', function() {
      it('should call deleteCollectionNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test deleteCollectionNamespacedScheduledJob
        //instance.deleteCollectionNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNamespacedCronJob', function() {
      it('should call deleteNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test deleteNamespacedCronJob
        //instance.deleteNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNamespacedScheduledJob', function() {
      it('should call deleteNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test deleteNamespacedScheduledJob
        //instance.deleteNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAPIResources', function() {
      it('should call getAPIResources successfully', function(done) {
        //uncomment below and update the code to test getAPIResources
        //instance.getAPIResources(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCronJobForAllNamespaces', function() {
      it('should call listCronJobForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test listCronJobForAllNamespaces
        //instance.listCronJobForAllNamespaces(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listNamespacedCronJob', function() {
      it('should call listNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test listNamespacedCronJob
        //instance.listNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listNamespacedScheduledJob', function() {
      it('should call listNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test listNamespacedScheduledJob
        //instance.listNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listScheduledJobForAllNamespaces', function() {
      it('should call listScheduledJobForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test listScheduledJobForAllNamespaces
        //instance.listScheduledJobForAllNamespaces(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNamespacedCronJob', function() {
      it('should call patchNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test patchNamespacedCronJob
        //instance.patchNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNamespacedCronJobStatus', function() {
      it('should call patchNamespacedCronJobStatus successfully', function(done) {
        //uncomment below and update the code to test patchNamespacedCronJobStatus
        //instance.patchNamespacedCronJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNamespacedScheduledJob', function() {
      it('should call patchNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test patchNamespacedScheduledJob
        //instance.patchNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNamespacedScheduledJobStatus', function() {
      it('should call patchNamespacedScheduledJobStatus successfully', function(done) {
        //uncomment below and update the code to test patchNamespacedScheduledJobStatus
        //instance.patchNamespacedScheduledJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNamespacedCronJob', function() {
      it('should call readNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test readNamespacedCronJob
        //instance.readNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNamespacedCronJobStatus', function() {
      it('should call readNamespacedCronJobStatus successfully', function(done) {
        //uncomment below and update the code to test readNamespacedCronJobStatus
        //instance.readNamespacedCronJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNamespacedScheduledJob', function() {
      it('should call readNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test readNamespacedScheduledJob
        //instance.readNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNamespacedScheduledJobStatus', function() {
      it('should call readNamespacedScheduledJobStatus successfully', function(done) {
        //uncomment below and update the code to test readNamespacedScheduledJobStatus
        //instance.readNamespacedScheduledJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceNamespacedCronJob', function() {
      it('should call replaceNamespacedCronJob successfully', function(done) {
        //uncomment below and update the code to test replaceNamespacedCronJob
        //instance.replaceNamespacedCronJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceNamespacedCronJobStatus', function() {
      it('should call replaceNamespacedCronJobStatus successfully', function(done) {
        //uncomment below and update the code to test replaceNamespacedCronJobStatus
        //instance.replaceNamespacedCronJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceNamespacedScheduledJob', function() {
      it('should call replaceNamespacedScheduledJob successfully', function(done) {
        //uncomment below and update the code to test replaceNamespacedScheduledJob
        //instance.replaceNamespacedScheduledJob(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceNamespacedScheduledJobStatus', function() {
      it('should call replaceNamespacedScheduledJobStatus successfully', function(done) {
        //uncomment below and update the code to test replaceNamespacedScheduledJobStatus
        //instance.replaceNamespacedScheduledJobStatus(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
