/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.displayName = 'proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getField(msg, 1),
    name: jspb.Message.getField(msg, 2),
    uid: jspb.Message.getField(msg, 3),
    resourceversion: jspb.Message.getField(msg, 4),
    kubeletconfigkey: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource;
  return proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceversion(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setKubeletconfigkey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.setNamespace = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.clearNamespace = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.hasNamespace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.clearName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.hasName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string uid = 3;
 * @return {string}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.setUid = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.clearUid = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.hasUid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string resourceVersion = 4;
 * @return {string}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.getResourceversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.setResourceversion = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.clearResourceversion = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.hasResourceversion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string kubeletConfigKey = 5;
 * @return {string}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.getKubeletconfigkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.setKubeletconfigkey = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.clearKubeletconfigkey = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.ConfigMapNodeConfigSource.prototype.hasKubeletconfigkey = function() {
  return jspb.Message.getField(this, 5) != null;
};


