/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.core.v1.FCVolumeSource');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.core.v1.FCVolumeSource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.api.core.v1.FCVolumeSource.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.api.core.v1.FCVolumeSource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.core.v1.FCVolumeSource.displayName = 'proto.k8s.io.api.core.v1.FCVolumeSource';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.api.core.v1.FCVolumeSource.repeatedFields_ = [1,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.core.v1.FCVolumeSource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.core.v1.FCVolumeSource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.FCVolumeSource.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetwwnsList: jspb.Message.getRepeatedField(msg, 1),
    lun: jspb.Message.getField(msg, 2),
    fstype: jspb.Message.getField(msg, 3),
    readonly: jspb.Message.getField(msg, 4),
    wwidsList: jspb.Message.getRepeatedField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.core.v1.FCVolumeSource}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.core.v1.FCVolumeSource;
  return proto.k8s.io.api.core.v1.FCVolumeSource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.core.v1.FCVolumeSource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.core.v1.FCVolumeSource}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addTargetwwns(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLun(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFstype(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadonly(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addWwids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.core.v1.FCVolumeSource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.core.v1.FCVolumeSource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.FCVolumeSource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetwwnsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getWwidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * repeated string targetWWNs = 1;
 * @return {!Array<string>}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.getTargetwwnsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.setTargetwwnsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.addTargetwwns = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.k8s.io.api.core.v1.FCVolumeSource.prototype.clearTargetwwnsList = function() {
  this.setTargetwwnsList([]);
};


/**
 * optional int32 lun = 2;
 * @return {number}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.getLun = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.setLun = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.k8s.io.api.core.v1.FCVolumeSource.prototype.clearLun = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.hasLun = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string fsType = 3;
 * @return {string}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.getFstype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.setFstype = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.k8s.io.api.core.v1.FCVolumeSource.prototype.clearFstype = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.hasFstype = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool readOnly = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.getReadonly = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.setReadonly = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.k8s.io.api.core.v1.FCVolumeSource.prototype.clearReadonly = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.hasReadonly = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string wwids = 5;
 * @return {!Array<string>}
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.getWwidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.setWwidsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.k8s.io.api.core.v1.FCVolumeSource.prototype.addWwids = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.k8s.io.api.core.v1.FCVolumeSource.prototype.clearWwidsList = function() {
  this.setWwidsList([]);
};


