/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.extensions.v1beta1.IDRange');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.displayName = 'proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    rule: jspb.Message.getField(msg, 1),
    rangesList: jspb.Message.toObjectList(msg.getRangesList(),
    proto.k8s.io.api.extensions.v1beta1.IDRange.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions;
  return proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRule(value);
      break;
    case 2:
      var value = new proto.k8s.io.api.extensions.v1beta1.IDRange;
      reader.readMessage(value,proto.k8s.io.api.extensions.v1beta1.IDRange.deserializeBinaryFromReader);
      msg.addRanges(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRangesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.k8s.io.api.extensions.v1beta1.IDRange.serializeBinaryToWriter
    );
  }
};


/**
 * optional string rule = 1;
 * @return {string}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.getRule = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.setRule = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.clearRule = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.hasRule = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated IDRange ranges = 2;
 * @return {!Array<!proto.k8s.io.api.extensions.v1beta1.IDRange>}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.getRangesList = function() {
  return /** @type{!Array<!proto.k8s.io.api.extensions.v1beta1.IDRange>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8s.io.api.extensions.v1beta1.IDRange, 2));
};


/** @param {!Array<!proto.k8s.io.api.extensions.v1beta1.IDRange>} value */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.setRangesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.k8s.io.api.extensions.v1beta1.IDRange=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8s.io.api.extensions.v1beta1.IDRange}
 */
proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.addRanges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.k8s.io.api.extensions.v1beta1.IDRange, opt_index);
};


proto.k8s.io.api.extensions.v1beta1.FSGroupStrategyOptions.prototype.clearRangesList = function() {
  this.setRangesList([]);
};


