/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.core.v1.PersistentVolumeClaim');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec');
goog.require('proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus');
goog.require('proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8s.io.api.core.v1.PersistentVolumeClaim, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.core.v1.PersistentVolumeClaim.displayName = 'proto.k8s.io.api.core.v1.PersistentVolumeClaim';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.core.v1.PersistentVolumeClaim.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaim} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.toObject(includeInstance, f),
    spec: (f = msg.getSpec()) && proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.core.v1.PersistentVolumeClaim}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.core.v1.PersistentVolumeClaim;
  return proto.k8s.io.api.core.v1.PersistentVolumeClaim.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaim} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.core.v1.PersistentVolumeClaim}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta;
      reader.readMessage(value,proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec;
      reader.readMessage(value,proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec.deserializeBinaryFromReader);
      msg.setSpec(value);
      break;
    case 3:
      var value = new proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus;
      reader.readMessage(value,proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.core.v1.PersistentVolumeClaim.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaim} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.serializeBinaryToWriter
    );
  }
  f = message.getSpec();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta metadata = 1;
 * @return {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.getMetadata = function() {
  return /** @type{?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta} */ (
    jspb.Message.getWrapperField(this, proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta, 1));
};


/** @param {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta|undefined} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PersistentVolumeClaimSpec spec = 2;
 * @return {?proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.getSpec = function() {
  return /** @type{?proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec} */ (
    jspb.Message.getWrapperField(this, proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec, 2));
};


/** @param {?proto.k8s.io.api.core.v1.PersistentVolumeClaimSpec|undefined} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.setSpec = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.clearSpec = function() {
  this.setSpec(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.hasSpec = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PersistentVolumeClaimStatus status = 3;
 * @return {?proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.getStatus = function() {
  return /** @type{?proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus} */ (
    jspb.Message.getWrapperField(this, proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus, 3));
};


/** @param {?proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus|undefined} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.setStatus = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.clearStatus = function() {
  this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaim.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 3) != null;
};


