/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition');
goog.require('proto.k8s.io.apimachinery.pkg.api.resource.Quantity');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.displayName = 'proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.repeatedFields_ = [2,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    phase: jspb.Message.getField(msg, 1),
    accessmodesList: jspb.Message.getRepeatedField(msg, 2),
    capacityMap: (f = msg.getCapacityMap()) ? f.toObject(includeInstance, proto.k8s.io.apimachinery.pkg.api.resource.Quantity.toObject) : [],
    conditionsList: jspb.Message.toObjectList(msg.getConditionsList(),
    proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus;
  return proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAccessmodes(value);
      break;
    case 3:
      var value = msg.getCapacityMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.k8s.io.apimachinery.pkg.api.resource.Quantity.deserializeBinaryFromReader, "");
         });
      break;
    case 4:
      var value = new proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition;
      reader.readMessage(value,proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition.deserializeBinaryFromReader);
      msg.addConditions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAccessmodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getCapacityMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.k8s.io.apimachinery.pkg.api.resource.Quantity.serializeBinaryToWriter);
  }
  f = message.getConditionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition.serializeBinaryToWriter
    );
  }
};


/**
 * optional string phase = 1;
 * @return {string}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.getPhase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.setPhase = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.clearPhase = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.hasPhase = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string accessModes = 2;
 * @return {!Array<string>}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.getAccessmodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.setAccessmodesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.addAccessmodes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.clearAccessmodesList = function() {
  this.setAccessmodesList([]);
};


/**
 * map<string, k8s.io.apimachinery.pkg.api.resource.Quantity> capacity = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.k8s.io.apimachinery.pkg.api.resource.Quantity>}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.getCapacityMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.k8s.io.apimachinery.pkg.api.resource.Quantity>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.k8s.io.apimachinery.pkg.api.resource.Quantity));
};


proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.clearCapacityMap = function() {
  this.getCapacityMap().clear();
};


/**
 * repeated PersistentVolumeClaimCondition conditions = 4;
 * @return {!Array<!proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition>}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.getConditionsList = function() {
  return /** @type{!Array<!proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition, 4));
};


/** @param {!Array<!proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition>} value */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.setConditionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition}
 */
proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.addConditions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.k8s.io.api.core.v1.PersistentVolumeClaimCondition, opt_index);
};


proto.k8s.io.api.core.v1.PersistentVolumeClaimStatus.prototype.clearConditionsList = function() {
  this.setConditionsList([]);
};


