/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget');
goog.require('proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.displayName = 'proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList;
  return proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta;
      reader.readMessage(value,proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget;
      reader.readMessage(value,proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget.serializeBinaryToWriter
    );
  }
};


/**
 * optional k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 1;
 * @return {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.getMetadata = function() {
  return /** @type{?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta} */ (
    jspb.Message.getWrapperField(this, proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta, 1));
};


/** @param {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta|undefined} value */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated PodDisruptionBudget items = 2;
 * @return {!Array<!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget>}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget, 2));
};


/** @param {!Array<!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget>} value */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget}
 */
proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.k8s.io.api.policy.v1beta1.PodDisruptionBudget, opt_index);
};


proto.k8s.io.api.policy.v1beta1.PodDisruptionBudgetList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};


