/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.core.v1.Probe');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.core.v1.Handler');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.core.v1.Probe = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.k8s.io.api.core.v1.Probe, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.core.v1.Probe.displayName = 'proto.k8s.io.api.core.v1.Probe';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.core.v1.Probe.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.core.v1.Probe.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.core.v1.Probe} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.Probe.toObject = function(includeInstance, msg) {
  var f, obj = {
    handler: (f = msg.getHandler()) && proto.k8s.io.api.core.v1.Handler.toObject(includeInstance, f),
    initialdelayseconds: jspb.Message.getField(msg, 2),
    timeoutseconds: jspb.Message.getField(msg, 3),
    periodseconds: jspb.Message.getField(msg, 4),
    successthreshold: jspb.Message.getField(msg, 5),
    failurethreshold: jspb.Message.getField(msg, 6)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.core.v1.Probe}
 */
proto.k8s.io.api.core.v1.Probe.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.core.v1.Probe;
  return proto.k8s.io.api.core.v1.Probe.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.core.v1.Probe} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.core.v1.Probe}
 */
proto.k8s.io.api.core.v1.Probe.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.k8s.io.api.core.v1.Handler;
      reader.readMessage(value,proto.k8s.io.api.core.v1.Handler.deserializeBinaryFromReader);
      msg.setHandler(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInitialdelayseconds(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimeoutseconds(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeriodseconds(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSuccessthreshold(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFailurethreshold(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.core.v1.Probe.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.core.v1.Probe.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.core.v1.Probe} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.core.v1.Probe.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHandler();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.k8s.io.api.core.v1.Handler.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional Handler handler = 1;
 * @return {?proto.k8s.io.api.core.v1.Handler}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getHandler = function() {
  return /** @type{?proto.k8s.io.api.core.v1.Handler} */ (
    jspb.Message.getWrapperField(this, proto.k8s.io.api.core.v1.Handler, 1));
};


/** @param {?proto.k8s.io.api.core.v1.Handler|undefined} value */
proto.k8s.io.api.core.v1.Probe.prototype.setHandler = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearHandler = function() {
  this.setHandler(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasHandler = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 initialDelaySeconds = 2;
 * @return {number}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getInitialdelayseconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.Probe.prototype.setInitialdelayseconds = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearInitialdelayseconds = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasInitialdelayseconds = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 timeoutSeconds = 3;
 * @return {number}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getTimeoutseconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.Probe.prototype.setTimeoutseconds = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearTimeoutseconds = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasTimeoutseconds = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 periodSeconds = 4;
 * @return {number}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getPeriodseconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.Probe.prototype.setPeriodseconds = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearPeriodseconds = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasPeriodseconds = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 successThreshold = 5;
 * @return {number}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getSuccessthreshold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.Probe.prototype.setSuccessthreshold = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearSuccessthreshold = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasSuccessthreshold = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 failureThreshold = 6;
 * @return {number}
 */
proto.k8s.io.api.core.v1.Probe.prototype.getFailurethreshold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.k8s.io.api.core.v1.Probe.prototype.setFailurethreshold = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.k8s.io.api.core.v1.Probe.prototype.clearFailurethreshold = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.core.v1.Probe.prototype.hasFailurethreshold = function() {
  return jspb.Message.getField(this, 6) != null;
};


