/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.k8s.io.api.authentication.v1beta1.UserInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.k8s.io.api.authentication.v1beta1.ExtraValue');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.api.authentication.v1beta1.UserInfo.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.api.authentication.v1beta1.UserInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.k8s.io.api.authentication.v1beta1.UserInfo.displayName = 'proto.k8s.io.api.authentication.v1beta1.UserInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.api.authentication.v1beta1.UserInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.api.authentication.v1beta1.UserInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getField(msg, 1),
    uid: jspb.Message.getField(msg, 2),
    groupsList: jspb.Message.getRepeatedField(msg, 3),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, proto.k8s.io.api.authentication.v1beta1.ExtraValue.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.api.authentication.v1beta1.UserInfo}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.api.authentication.v1beta1.UserInfo;
  return proto.k8s.io.api.authentication.v1beta1.UserInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.api.authentication.v1beta1.UserInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.api.authentication.v1beta1.UserInfo}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addGroups(value);
      break;
    case 4:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.k8s.io.api.authentication.v1beta1.ExtraValue.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.api.authentication.v1beta1.UserInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.api.authentication.v1beta1.UserInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGroupsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.k8s.io.api.authentication.v1beta1.ExtraValue.serializeBinaryToWriter);
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.setUsername = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.clearUsername = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.hasUsername = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string uid = 2;
 * @return {string}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.setUid = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.clearUid = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.hasUid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string groups = 3;
 * @return {!Array<string>}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.getGroupsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.setGroupsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.addGroups = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.clearGroupsList = function() {
  this.setGroupsList([]);
};


/**
 * map<string, ExtraValue> extra = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.k8s.io.api.authentication.v1beta1.ExtraValue>}
 */
proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.k8s.io.api.authentication.v1beta1.ExtraValue>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.k8s.io.api.authentication.v1beta1.ExtraValue));
};


proto.k8s.io.api.authentication.v1beta1.UserInfo.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};


