name: Kubernetes Javascript Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '14', '12' ]
    name: Node ${{ matrix.node }} validation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # Pre-check to validate that versions match between package.json
      # and package-lock.json. Needs to run before npm install
      - run: node version-check.js
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm audit --audit-level=critical
  release-package:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      # Pre-check to validate that versions match between package.json
      # and package-lock.json. Needs to run before npm install
      - name: Validate package.json and package-lock.json versions
        run: node version-check.js
      - name: Install dependencies
        run: npm ci
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: github.event_name == 'pull_request'

