name: Build and Deploy Docs
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'typedoc.json'
            - 'package.json'
            - 'package-lock.json'
            - '.github/workflows/deploy-docs.yml'

permissions: {}

jobs:
    build-and-deploy-docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - name: Setup Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: '22'
            # Pre-check to validate that versions match between package.json
            # and package-lock.json. Needs to run before npm install
            - name: Validate package.json and package-lock.json versions
              run: node version-check.js
            - name: Install dependencies
              run: npm ci
            - name: Build docs
              run: npm run docs

            - name: Deploy docs
              uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: docs # The folder the action should deploy.
