name: Kubernetes Javascript Client - Validation

on:
    push:
        branches: [master, main]
        paths:
            - 'src/**'
            - 'testdata/**'
            - 'package.json'
            - 'package-lock.json'
            - 'tsconfig*.json'
            - 'eslint.config.js'
            - 'version-check.js'
            - '.github/workflows/test.yml'
    pull_request:
        branches: [master, main]
        paths:
            - 'src/**'
            - 'testdata/**'
            - 'package.json'
            - 'package-lock.json'
            - 'tsconfig*.json'
            - 'eslint.config.js'
            - 'version-check.js'
            - '.github/workflows/test.yml'

permissions: {}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        strategy:
            matrix:
                node: ['26', '25', '24', '22']
        name: Node ${{ matrix.node }} validation
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{ matrix.node }}
            # Pre-check to validate that versions match between package.json
            # and package-lock.json. Needs to run before npm install
            - run: node version-check.js
            - run: npm ci
            - run: npm test
            - run: npm run lint
            - run: npm audit --audit-level=critical
            - run: npm run build-with-tests && npm run test-transpiled
            - name: Create k8s Kind Cluster
              uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
            - run: npm run integration-test
    zizmor:
        runs-on: ubuntu-latest
        name: GitHub Actions security lint
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
              with:
                  advanced-security: false
                  persona: pedantic
                  min-severity: medium
